//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DumpApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admLicenseSetUp
    {
        [Key]
        public int Itbid { get; set; }
        public string LincenseKey { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
