//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DumpApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admMenuControl
    {
        [Key]
        public int menu_id { get; set; }
        public string menu_name { get; set; }
        public string action { get; set; }
        public string controller { get; set; }
        public Nullable<int> parent { get; set; }
        public Nullable<short> priority { get; set; }
        public string status { get; set; }
        public string css_class { get; set; }
        public Nullable<bool> flag { get; set; }
    }
}
