//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DumpApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class admRoleAssignment
    {
        public int id { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> menu_id { get; set; }
        public Nullable<short> can_view { get; set; }
        public Nullable<short> can_add { get; set; }
        public Nullable<short> can_edit { get; set; }
        public Nullable<short> can_auth { get; set; }
        public Nullable<short> can_delete { get; set; }
        public Nullable<short> is_global_supervisor { get; set; }
    }
}
