//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DumpApp.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DumpAppEntities : DbContext
    {
        public DumpAppEntities()
            : base("name=DumpAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admAuditTrail> admAuditTrails { get; set; }
        public virtual DbSet<admClientProfile> admClientProfiles { get; set; }
        public virtual DbSet<admRole> admRoles { get; set; }
        public virtual DbSet<admRoleAssignment> admRoleAssignments { get; set; }
        public virtual DbSet<admStatusItem> admStatusItems { get; set; }
        public virtual DbSet<admUserProfile> admUserProfiles { get; set; }
        public virtual DbSet<admMenuControl> admMenuControls { get; set; }
        public virtual DbSet<admUserLogin> admUserLogins { get; set; }
        public virtual DbSet<admDumpType> admDumpTypes { get; set; }
        public virtual DbSet<admDatabase> admDatabases { get; set; }
        public virtual DbSet<admDump> admDumps { get; set; }
        public virtual DbSet<admLocation> admLocations { get; set; }
        public virtual DbSet<admTapeDevice> admTapeDevices { get; set; }
        public virtual DbSet<admLoad> admLoads { get; set; }
    
        public virtual ObjectResult<Isp_MenuSystemAdmin_Result> Isp_MenuSystemAdmin(Nullable<int> role_id)
        {
            var role_idParameter = role_id.HasValue ?
                new ObjectParameter("role_id", role_id) :
                new ObjectParameter("role_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Isp_MenuSystemAdmin_Result>("Isp_MenuSystemAdmin", role_idParameter);
        }
    
        public virtual ObjectResult<Isp_MenuSystemOperations_Result> Isp_MenuSystemOperations(Nullable<int> role_id)
        {
            var role_idParameter = role_id.HasValue ?
                new ObjectParameter("role_id", role_id) :
                new ObjectParameter("role_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Isp_MenuSystemOperations_Result>("Isp_MenuSystemOperations", role_idParameter);
        }
    
        public virtual ObjectResult<Isp_MenuSystemReports_Result> Isp_MenuSystemReports(Nullable<int> role_id)
        {
            var role_idParameter = role_id.HasValue ?
                new ObjectParameter("role_id", role_id) :
                new ObjectParameter("role_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Isp_MenuSystemReports_Result>("Isp_MenuSystemReports", role_idParameter);
        }
    }
}
